package frc.robot.subsystems.drive;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.commands.PathfindingCommand;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

import frc.robot.Constants;
import frc.robot.subsystems.drive.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.localisation.LimelightHelpers;
import frc.robot.subsystems.localisation.LimelightInfo;
import frc.robot.subsystems.localisation.LocalisationConstants;
import frc.robot.subsystems.shooter.ShooterConstants;
import frc.robot.util.LoggedTunableNumber;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private final Field2d m_field = new Field2d();
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();
    // Heading-locked drive request shared by faceHubCommand; PID configured in configureAutoBuilder.
    private final SwerveRequest.FieldCentricFacingAngle snapRequest = new SwerveRequest.FieldCentricFacingAngle();
    // Counts how many times vision has reset the pose. If this isn't climbing while a
    // tag is in view, vision positioning is broken -- check the Limelight name and NT.
    private int m_visionPoseResets = 0;

    // Live aim trim (degrees). Corrects a constant left/right bias in where shots land,
    // e.g. the shooter not sitting perfectly square on the frame. Tune on the field in
    // 1-degree steps: if shots move the wrong way, flip the sign. Bake the final value
    // into the default here once dialed in.
    private final LoggedTunableNumber m_headingOffsetDeg =
        new LoggedTunableNumber("ShotTuning/HeadingOffsetDeg", 0);

    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;
    private Optional<Alliance> m_lastAlliance = Optional.empty();

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),
                    // PID constants for rotation
                    new PIDConstants(7, 0, 0)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }

        m_lastAlliance = Optional.of(DriverStation.getAlliance().orElse(Alliance.Blue));
        updateAllianceDependentState();
        // P turns toward the hub; the small D damps the approach so it settles instead of
        // overshooting and hunting. If aim chatters at rest, lower D first, then P.
        snapRequest.HeadingController.setPID(8, 0, 0.2);
        snapRequest.HeadingController.enableContinuousInput(-Math.PI, Math.PI);

        SmartDashboard.putData("Field", m_field);
        CommandScheduler.getInstance().schedule(PathfindingCommand.warmupCommand());
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    private void updateAllianceDependentState() {
        DriverStation.getAlliance().ifPresent(allianceColor -> {
            m_lastAlliance = Optional.of(allianceColor);

            if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            }
        });
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        updateAllianceDependentState();

        // === Vision-direct positioning (Limelight is the pose source) ===
        // Whenever the camera sees at least one tag, the robot pose is snapped straight
        // to the vision estimate: vision XY + current gyro heading. No Kalman fusion, no
        // outlier gating -- what the Limelight says is where we are.
        //
        // Always read the BLUE-origin botpose regardless of alliance. Everything else in
        // this codebase (Field2d, hub positions, trench Y bounds, PathPlanner) uses the
        // WPILib always-blue-origin convention, so red-origin botpose would be mirrored
        // ~16 m away. Alliance only affects driver perspective and which hub we target.
        //
        // NOTE: the pose is reset imperatively with resetPose(). Do NOT route this through
        // a Command-returning helper -- an unscheduled Command silently does nothing (this
        // exact bug shipped twice: lintake stow, then vision seeding).
        boolean hubVisible = false;
        for (LimelightInfo limelight : LocalisationConstants.kLimelights) {
            // Give the camera our heading + yaw rate (needed if we ever switch to MegaTag2;
            // harmless for the MegaTag1 botpose read below).
            LimelightHelpers.SetRobotOrientation(
                    limelight.name(), getState().Pose.getRotation().getDegrees(),
                    getPigeon2().getAngularVelocityZWorld().getValueAsDouble(),
                    0, 0, 0, 0
                );

            final LimelightHelpers.PoseEstimate estimate =
                LimelightHelpers.getBotPoseEstimate_wpiBlue(limelight.name());

            if (estimate == null || estimate.tagCount == 0) {
                continue;  // No tags in view; keep the last pose (odometry carries it)
            }
            hubVisible = true;

            // Vision XY, gyro heading. Vision heading jitters a few degrees frame to
            // frame; the Pigeon is far more stable, so it keeps owning rotation.
            //
            // 3 cm deadband: single-tag botpose jitters a centimeter or two between
            // frames even when the robot is bolted still. Resetting the pose with that
            // noise makes the aim target vibrate (which the heading controller then
            // chases). Inside the deadband, odometry carries the pose smoothly.
            double visionDelta = estimate.pose.getTranslation()
                .getDistance(getState().Pose.getTranslation());
            if (visionDelta > 0.03) {
                resetPose(new Pose2d(
                    estimate.pose.getTranslation(),
                    getState().Pose.getRotation()
                ));
                m_visionPoseResets++;
            }

            // Raw vision diagnostics -- compare these against where the robot actually is.
            SmartDashboard.putNumber("vision/pose x", estimate.pose.getX());
            SmartDashboard.putNumber("vision/pose y", estimate.pose.getY());
            SmartDashboard.putNumber("vision/tag count", estimate.tagCount);
            SmartDashboard.putNumber("vision/avg tag dist", estimate.avgTagDist);
        }

        // === Dashboard diagnostics ===
        m_field.setRobotPose(getState().Pose);
        SmartDashboard.putNumber("dist to hub", this.getDistanceToClosestHub());
        SmartDashboard.putBoolean("hub visible", hubVisible);  // True if any tags detected
        SmartDashboard.putNumber("vision/pose resets", m_visionPoseResets);
        // Publish which alliance's hub is currently active per 2026 Game Data logic
        double matchTime = DriverStation.getMatchTime();
        String gameData = DriverStation.getGameSpecificMessage();

        boolean ourHubActive = computeOurHubActive(matchTime, gameData);
        SmartDashboard.putBoolean("our hub active", ourHubActive);

        // Compute which alliance currently has active hub (Blue or Red)
        boolean blueHubActive = computeHubActiveForAlliance(Alliance.Blue, matchTime, gameData);
        String activeAlliance = blueHubActive ? "Blue" : "Red";
        SmartDashboard.putString("active hub alliance", activeAlliance);
    }

    private boolean computeOurHubActive(double matchTime, String gameData) {
        return DriverStation.getAlliance()
            .map(alliance -> computeHubActiveForAlliance(alliance, matchTime, gameData))
            .orElse(false);
    }

    /** 2026 game-data hub logic: hubs alternate 25 s active shifts through teleop, with the
     *  order set by the first character of the game data ('R' = red inactive first). */
    private boolean computeHubActiveForAlliance(Alliance alliance, double matchTime, String gameData) {
        if (DriverStation.isAutonomous()) {
            return true;
        }
        if (!DriverStation.isTeleop()) {
            return false;
        }
        // If no game data yet, assume hub active (per WPILib guidance)
        if (gameData == null || gameData.isEmpty()) {
            return true;
        }
        boolean redInactiveFirst;
        switch (gameData.charAt(0)) {
            case 'R' -> redInactiveFirst = true;
            case 'B' -> redInactiveFirst = false;
            default -> {
                return true;
            }
        }

        boolean shift1Active = switch (alliance) {
            case Red -> !redInactiveFirst;
            case Blue -> redInactiveFirst;
        };

        if (matchTime > 130) {
            return true;
        } else if (matchTime > 105) {
            return shift1Active;
        } else if (matchTime > 80) {
            return !shift1Active;
        } else if (matchTime > 55) {
            return shift1Active;
        } else if (matchTime > 30) {
            return !shift1Active;
        } else {
            return true;
        }
    }


    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }
    public double getDistanceToClosestHub() {
        return getState().Pose.getTranslation().getDistance(getHubPosition());
    }

    public Translation2d getHubPosition() {
        return DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red
            ? ShooterConstants.kRedHubPosition
            : ShooterConstants.kBlueHubPosition;
    }

    public ChassisSpeeds getFieldRelativeSpeeds() {
        return ChassisSpeeds.fromRobotRelativeSpeeds(getState().Speeds, getState().Pose.getRotation());
    }

    // === Shot time-of-flight ===
    // Look up the time for the ball to reach the hub at the current distance. The offset
    // (dashboard-tunable) accounts for release height, drag, and any frame-to-frame delay.
    public double getShotTimeOfFlightSeconds() {
        double offset = SmartDashboard.getNumber(ShooterConstants.kTimeOfFlightOffsetKey, 0);
        return Math.max(0.001, ShooterConstants.getShotTimeOfFlightSeconds(getDistanceToClosestHub()) + offset);
    }

    // === Shoot-on-the-move: motion compensation ===
    // PROBLEM: A stationary robot aims at the hub's current position. A moving robot
    // must aim at where the hub will be when the ball arrives. At 6 m/s robot speed,
    // 0.8 s ball flight, the hub moves ~4.8 m in the ball's frame. Not accounting for
    // this causes the shot to miss by meters.
    //
    // SOLUTION: Compute a "virtual hub position" (in robot-relative space) that
    // accounts for the robot's motion. When the robot aims at this position, the ball
    // trajectory intersects the actual hub.
    //
    // MATHEMATICAL DERIVATION:
    //   We want to find the aiming direction d such that, if the ball is launched at
    //   speed v in direction d (from the robot's current position), and the robot
    //   continues at its current velocity v_robot for time TOF, the ball will intersect
    //   the hub at the hub's future position.
    //
    //   In field space:
    //     ball_final = robot_pos + ball_displacement
    //     hub_final = hub_pos + robot_velocity * TOF
    //     We want: ball_final = hub_final
    //     → ball_displacement = (hub_pos + robot_vel * TOF) - robot_pos
    //     → ball_displacement = (hub_pos - robot_pos) + robot_vel * TOF
    //
    //   But the ball flies in a ballistic arc. What matters is the *average* velocity
    //   the ball must maintain to cover the displacement in time TOF. This is derived
    //   from the shot table's physics; for now, assume the table's distance and TOF
    //   directly yield the required ball velocity magnitude and direction.
    //
    //   In robot space:
    //     The robot sees the hub at a certain bearing. But because the robot is moving,
    //     the relative position changes over TOF. The required ball velocity (in field
    //     space) is:
    //       v_ball_field = (hub_pos - robot_pos + robot_vel * TOF) / TOF
    //                     = (hub_pos - robot_pos) / TOF + robot_vel
    //
    //     From the robot's perspective (in robot body frame), the required velocity is:
    //       v_ball_robot = v_ball_field - v_robot
    //                     = (hub_pos - robot_pos) / TOF + robot_vel - robot_vel
    //                     = (hub_pos - robot_pos) / TOF
    //       Wait, that can't be right...
    //
    //   Actually, let's think differently. The robot fires the ball at some speed in
    //   some direction. That speed is determined by the shot table (e.g., 30 RPS for
    //   3.5 m). The direction is what we compute. The ball, once fired, follows a
    //   ballistic path in field space. For the ball to hit the hub at the hub's future
    //   position, the initial launch direction must account for the hub's motion relative
    //   to the robot.
    //
    //   Here's the correct model:
    //   - The hub is at position H in field space.
    //   - The robot is at position R and moving at velocity v_r (field frame).
    //   - In time TOF, the hub moves to H + v_hub * TOF ≈ H (hub is stationary on field).
    //   - The robot will be at R + v_r * TOF.
    //   - We want the ball to reach the hub. The relative position at end of flight is:
    //       hub_end - robot_end = H - (R + v_r * TOF) = (H - R) - v_r * TOF
    //   - But wait, the robot is accelerating with the ball, so the initial relative
    //     position is (H - R). The ball must cover a distance that accounts for the
    //     robot moving away (or toward) the hub during flight.
    //   - The net displacement in the robot's frame is:
    //       displacement_robot = (H - R) - v_r * TOF
    //   - This is the distance the ball must travel *in the robot's frame* to hit the hub.
    //   - BUT: the ball is launched in the robot's body frame, not the field frame.
    //     In the robot's body frame, the ball flies straight (ignoring gravity for
    //     horizontal aiming). So the direction to aim is the angle of this displacement.
    //
    //   CODE DERIVATION:
    //   - robotToHub = H - R (field frame)
    //   - requiredFieldVelocity = robotToHub / TOF (field velocity needed)
    //   - requiredRobotVelocity = requiredFieldVelocity - v_r (relative velocity)
    //   - shotVector = requiredRobotVelocity * TOF (integrate to displacement)
    //
    //   This is equivalent to:
    //   - shotVector = (robotToHub / TOF - v_r) * TOF
    //               = robotToHub - v_r * TOF
    //   Which is exactly the relative displacement we derived above!
    //
    // INTERPRETATION:
    //   The shot vector is the displacement in robot-relative space that the ball must
    //   cover to hit the hub, accounting for the robot's motion. If the robot is moving
    //   toward the hub, the required displacement shrinks. If moving away, it grows.
    //   If moving perpendicular to the hub, the shot vector rotates (aim perpendicular
    //   to the motion).
    //
    // ASSUMPTIONS:
    //   1. The ball follows a ballistic arc; we use the shot table's distance and TOF
    //      which encode the minimum-energy trajectory's hang time.
    //   2. The robot's velocity is constant over TOF. True for swerve; false if braking.
    //   3. The hub is stationary. True in *REBUILT*; false if the hub rotates or moves.
    //   4. Aiming is in the horizontal plane only. We ignore vertical motion.

    public Translation2d getMotionCompensatedShotVector() {
        Translation2d robotToHub = getHubPosition().minus(getState().Pose.getTranslation());
        double timeOfFlight = getShotTimeOfFlightSeconds();
        ChassisSpeeds fieldSpeeds = getFieldRelativeSpeeds();

        // Velocity the ball must maintain in field space to reach the hub's current position
        // in TOF seconds, starting from the robot's current position.
        Translation2d requiredFieldVelocity = robotToHub.div(timeOfFlight);

        // Relative velocity: what velocity the ball must have relative to the robot. This
        // accounts for the robot's own motion; if the robot is moving toward the hub, less
        // relative velocity is needed.
        Translation2d requiredRobotRelativeShotVelocity = requiredFieldVelocity.minus(
            new Translation2d(fieldSpeeds.vxMetersPerSecond, fieldSpeeds.vyMetersPerSecond)
        );

        // Integrate velocity over TOF to get the displacement vector. This is the distance
        // and bearing the robot should aim at to intersect the hub.
        return requiredRobotRelativeShotVelocity.times(timeOfFlight);
    }

    // === Compensated hub position (for visualization) ===
    // Where the hub will be in TOF seconds, given current robot motion.
    public Translation2d getCompensatedHubPosition() {
        return getState().Pose.getTranslation().plus(getMotionCompensatedShotVector());
    }

    // === Shot distance ===
    // Magnitude of the compensated shot vector, clamped to the table's valid range (0–6 m).
    public double getShotDistance() {
        return MathUtil.clamp(getMotionCompensatedShotVector().getNorm(), 0, 6);
    }


    // === Shot heading ===
    // Bearing of the motion-compensated shot vector, plus the fixed mechanical offset.
    //
    // NOTE: this used to add an "aim ahead while spinning" term (gyro rate x TOF). It was
    // removed on purpose -- do not add it back into this target. Two reasons:
    //   1. Feedback loop: the heading controller's own rotation fed the term, which pushed
    //      the target further ahead, which sped the rotation up (loop gain ~ P*TOF ~ 6).
    //      The robot oscillated around the hub and could never settle on it.
    //   2. Units: Pigeon getAngularVelocityZWorld() returns degrees/sec and the term used
    //      it as radians, so any rotation at all pinned the target 20 deg off the hub.
    // faceHubCommand drives the spin toward zero before the shot fires, so a spin term has
    // no value in the live aiming target. If spin compensation is ever truly needed, apply
    // it once at ball release, never inside the target the controller is chasing.
    public Rotation2d getHubHeading() {
        return getMotionCompensatedShotVector().getAngle()
            .plus(Rotation2d.fromDegrees(m_headingOffsetDeg.get()));
    }

    // === Heading error ===
    // How far off the robot's current heading is from the computed shot heading.
    // This is the readiness gate for aim (must be within 5°).
    public Rotation2d getHubHeadingError() {
        return Rotation2d.fromRadians(
            MathUtil.angleModulus(getHubHeading().minus(getState().Pose.getRotation()).getRadians())
        );
    }

    // === Face hub command ===
    // Heading-locked drive: the heading snaps to the computed hub heading (with PID stiffness),
    // while the driver retains full translation control. Used during aiming and charging shots.
    public Command faceHubCommand(Supplier<Double> xVelocity, Supplier<Double> yVelocity) {
        return applyRequest(() -> snapRequest
            .withVelocityX(xVelocity.get())
            .withVelocityY(yVelocity.get())
            .withDeadband(Constants.kMaxSpeed * 0.1)
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage)
            .withTargetDirection(getHubHeading())
        );
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}

