package frc.robot.subsystems.drive;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.commands.PathfindingCommand;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.filter.LinearFilter;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

import frc.robot.Constants;
import frc.robot.config.FeatureFlags;
import frc.robot.subsystems.drive.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.localisation.LimelightHelpers;
import frc.robot.subsystems.localisation.LimelightInfo;
import frc.robot.subsystems.localisation.LocalisationConstants;
import frc.robot.subsystems.shooter.ShooterConstants;
import frc.robot.util.LoggedTunableNumber;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private final Field2d m_field = new Field2d();
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();
    // Heading-locked drive request shared by faceHubCommand; PID configured in configureAutoBuilder.
    private final SwerveRequest.FieldCentricFacingAngle snapRequest = new SwerveRequest.FieldCentricFacingAngle();
    // Counts how many times vision has reset the pose. If this isn't climbing while a
    // tag is in view, vision positioning is broken -- check the Limelight name and NT.
    private int m_visionPoseResets = 0;

    // Whether a multi-tag vision heading has field-aligned the gyro yet. Until this is true,
    // aiming is trusting an unseeded gyro heading -- watch "vision/heading seeded" on the
    // dashboard before relying on aim (or just glance at a tag to seed it).
    private boolean m_headingSeededFromVision = false;
    // Re-align the gyro heading to a multi-tag vision heading only when they disagree by more
    // than this. Bigger than normal jitter/drift (a few degrees), so the Pigeon keeps owning
    // fine rotation and only a genuine divergence (bump, bad seed) triggers a re-align.
    private static final double kVisionHeadingSeedToleranceDegrees = 10.0;

    // Live aim trim (degrees). Corrects a constant left/right bias in where shots land,
    // e.g. the shooter not sitting perfectly square on the frame. Tune on the field in
    // 1-degree steps: if shots move the wrong way, flip the sign. Bake the final value
    // into the default here once dialed in.
    private final LoggedTunableNumber m_headingOffsetDeg =
        new LoggedTunableNumber("ShotTuning/HeadingOffsetDeg", 0);

    // Which side of the field the pass target sits on, with 0.5 m of hysteresis around
    // the centerline so the target (and the heading lock chasing it) can't flicker
    // between corners while driving down the middle.
    private boolean m_passHighSide = false;

    // How far the pass aim point sits in from the corner walls. Deliberately deep:
    // backspin bounces balls back toward the field on landing, so impact near the
    // corner settles the ball in the zone. Tune live watching where balls SETTLE.
    private final LoggedTunableNumber m_passCornerInset =
        new LoggedTunableNumber(ShooterConstants.kPassCornerInsetKey, ShooterConstants.kPassCornerInsetMeters);

    // --- Shoot-on-the-move solution state (computed once per loop in periodic) ---
    // Velocity lead is low-pass filtered and scaled by MoveCompGain: 1.0 = full physics
    // lead, 0 = aim as if stationary. 0.7 default deliberately under-leads -- the target
    // moves far less under the driver, at the cost of a little accuracy at max speed.
    private final LinearFilter m_shotVelFilterX = LinearFilter.singlePoleIIR(0.15, 0.02);
    private final LinearFilter m_shotVelFilterY = LinearFilter.singlePoleIIR(0.15, 0.02);
    private final LoggedTunableNumber m_moveCompGain =
        new LoggedTunableNumber("ShotTuning/MoveCompGain", 0.7);
    private Translation2d m_shotVector = new Translation2d(1, 0);
    private double m_shotTofSeconds = 0.5;

    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;
    private Optional<Alliance> m_lastAlliance = Optional.empty();

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),
                    // PID constants for rotation
                    new PIDConstants(7, 0, 0)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }

        m_lastAlliance = Optional.of(DriverStation.getAlliance().orElse(Alliance.Blue));
        updateAllianceDependentState();
        // P turns toward the hub; the small D damps the approach so it settles instead of
        // overshooting and hunting. If aim chatters at rest, lower D first, then P.
        snapRequest.HeadingController.setPID(8, 0, 0.2);
        snapRequest.HeadingController.enableContinuousInput(-Math.PI, Math.PI);

        SmartDashboard.putData("Field", m_field);
        CommandScheduler.getInstance().schedule(PathfindingCommand.warmupCommand());
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    // Runtime supply-current reallocation for the PowerManager. Re-applies a supply-only
    // current limit to all four drive motors (matching TunerConstants, which sets supply
    // only on the drive side -- traction is bounded separately by the 120 A slip current).
    // Config applies block for ~a millisecond each, so the PowerManager calls this from a
    // background thread; the short timeout keeps a missing device from hanging that thread.
    public void applyDriveSupplyCurrentLimit(double amps) {
        var limits = new com.ctre.phoenix6.configs.CurrentLimitsConfigs()
            .withSupplyCurrentLimit(amps)
            .withSupplyCurrentLimitEnable(true);
        for (int i = 0; i < 4; i++) {
            getModule(i).getDriveMotor().getConfigurator().apply(limits, 0.05);
        }
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    private void updateAllianceDependentState() {
        DriverStation.getAlliance().ifPresent(allianceColor -> {
            m_lastAlliance = Optional.of(allianceColor);

            if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
                m_operatorForwardDirection = allianceColor == Alliance.Red
                    ? kRedAlliancePerspectiveRotation
                    : kBlueAlliancePerspectiveRotation;
                setOperatorPerspectiveForward(m_operatorForwardDirection);
                m_hasAppliedOperatorPerspective = true;
            }
        });
    }

    // Mirror of the perspective handed to setOperatorPerspectiveForward -- kept so
    // fieldToOperatorBearing compensates with the EXACT rotation the swerve requests apply.
    private Rotation2d m_operatorForwardDirection = Rotation2d.kZero;

    /**
     * Converts an absolute blue-origin field bearing into the frame FieldCentricFacingAngle
     * expects. The request's default ForwardPerspective (OperatorPerspective) rotates
     * TargetDirection by the operator-forward direction -- 180 degrees when the DS alliance
     * is Red (verified in the Phoenix 26.1.0 sources, SwerveRequest.FieldCentricFacingAngle
     * .apply()). All of our aim targets (hub, pass corner, assist locks) are blue-origin
     * bearings, so WITHOUT this compensation every heading-locked feature pointed 180 deg
     * wrong on a Red DS: hub/pass aim faced away from the target, and the trench/tower
     * assist spun continuously (its nearest-90 lock re-snaps 60 deg into any rotation, so
     * the rotated target stayed ~180 deg ahead of the robot forever). Pre-rotating by the
     * inverse here makes the request's own rotation land back on the true field bearing.
     * Blue DS is a no-op; a 180 rotation is self-inverse, so the compensation cannot be
     * applied in the "wrong direction".
     */
    public Rotation2d fieldToOperatorBearing(Rotation2d fieldBearing) {
        return fieldBearing.rotateBy(m_operatorForwardDirection.unaryMinus());
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        updateAllianceDependentState();

        // === Vision localization: snap when lost, fuse when tracking ===
        // Two regimes, split by how far the vision estimate is from the current pose:
        //
        //   FAR OFF (> kMaxVisionCorrectionMeters): the pose is simply wrong (startup,
        //   robot carried, odometry ran blind too long). Snap: resetPose to vision XY +
        //   gyro heading. Fusing here would take seconds to converge; snapping is right.
        //
        //   CLOSE (<= threshold): normal tracking. Feed the estimate into the built-in
        //   Kalman filter (addVisionMeasurement) instead of hard-resetting. The filter
        //   blends vision with wheel odometry, which does two important things:
        //     1. Smooths single-tag botpose jitter so the aim target doesn't vibrate.
        //     2. Absorbs the garbage frames the camera produces right as a tag leaves
        //        the FOV (edge distortion + motion blur while rotating). A hard reset on
        //        one of those stranded the pose wrong just as vision went blind -- which
        //        is exactly when odometry needs a good starting point to carry the aim.
        //
        //   NO TAGS: odometry carries the pose from the last good fusion, so aiming
        //   keeps working when the tag leaves view (it drifts slowly, ~cm/s, vs. being
        //   frozen or wrong).
        //
        // Always read the BLUE-origin botpose regardless of alliance -- everything else
        // here (Field2d, hub positions, trench bounds, PathPlanner) is blue-origin.
        //
        // NOTE: pose changes go through resetPose()/addVisionMeasurement() imperatively.
        // Do NOT route them through a Command-returning helper -- an unscheduled Command
        // silently does nothing (that bug shipped twice: lintake stow, vision seeding).
        boolean hubVisible = false;
        for (LimelightInfo limelight : LocalisationConstants.kLimelights) {
            // Give the camera our heading + yaw rate (needed if we ever switch to MegaTag2;
            // harmless for the MegaTag1 botpose read below).
            LimelightHelpers.SetRobotOrientation(
                    limelight.name(), getState().Pose.getRotation().getDegrees(),
                    getPigeon2().getAngularVelocityZWorld().getValueAsDouble(),
                    0, 0, 0, 0
                );

            final LimelightHelpers.PoseEstimate estimate =
                LimelightHelpers.getBotPoseEstimate_wpiBlue(limelight.name());

            if (estimate == null || estimate.tagCount == 0) {
                continue;  // No tags in view; odometry carries the pose
            }
            hubVisible = true;

            double visionDelta = estimate.pose.getTranslation()
                .getDistance(getState().Pose.getTranslation());

            // FeatureFlags.VisionFusion off -> read + publish diagnostics but never touch the
            // pose (pure wheel odometry). The field escape hatch if the camera goes bad.
            if (FeatureFlags.VISION_FUSION.getAsBoolean()) {
                // === Heading field-alignment ===
                // The Pigeon still OWNS fine rotation (translation fusion below never touches
                // heading), but the gyro has to be field-aligned in the first place or every
                // aim is off by the misalignment forever -- there is no other heading
                // correction. So use MULTI-TAG botpose heading (unambiguous, unlike a single
                // tag) to seed that alignment: adopt it once, and re-adopt only if the gyro
                // has since diverged by more than the tolerance (a bump, a bad auto seed, or
                // no seed at all). Small disagreements are ignored, so normal jitter/drift is
                // left to the Pigeon and the aim target never chatters.
                Rotation2d headingToUse = getState().Pose.getRotation();
                boolean adoptVisionHeading = false;
                // Gated OFF by default: the seed trusts the Limelight mounting yaw, and a bad
                // camera pose flips the field-centric frame (reverses controls). With the flag
                // off, the gyro owns heading exactly as before -- snap keeps gyro rotation,
                // fuse never touches heading. Enable only after verifying the camera yaw.
                if (FeatureFlags.VISION_HEADING_SEED.getAsBoolean() && estimate.tagCount >= 2) {
                    double headingErrDeg = Math.toDegrees(Math.abs(MathUtil.angleModulus(
                        estimate.pose.getRotation().minus(getState().Pose.getRotation()).getRadians())));
                    if (!m_headingSeededFromVision || headingErrDeg > kVisionHeadingSeedToleranceDegrees) {
                        headingToUse = estimate.pose.getRotation();
                        adoptVisionHeading = true;
                        m_headingSeededFromVision = true;
                    }
                }

                if (visionDelta > ShooterConstants.kMaxVisionCorrectionMeters) {
                    // Grossly off: snap to vision XY (and the just-decided heading).
                    resetPose(new Pose2d(estimate.pose.getTranslation(), headingToUse));
                    m_visionPoseResets++;
                } else {
                    // Adopting a new heading this loop needs an explicit resetPose -- the
                    // Kalman fuse below is translation-only (infinite heading sigma).
                    if (adoptVisionHeading) {
                        resetPose(new Pose2d(getState().Pose.getTranslation(), headingToUse));
                    }
                    // Tracking: fuse translation. Trust falls off with tag distance -- close
                    // tags give centimeter solutions, far single tags wander. sigma = 0.05 +
                    // 0.02*d^2 (0.07 m at 1 m, 0.13 m at 2 m, 0.37 m at 4 m).
                    double xyStdDev = 0.05 + 0.02 * estimate.avgTagDist * estimate.avgTagDist;
                    addVisionMeasurement(
                        estimate.pose,
                        estimate.timestampSeconds,
                        VecBuilder.fill(xyStdDev, xyStdDev, Double.MAX_VALUE)
                    );
                }
            }

            // Raw vision diagnostics -- compare these against where the robot actually is.
            SmartDashboard.putNumber("vision/pose x", estimate.pose.getX());
            SmartDashboard.putNumber("vision/pose y", estimate.pose.getY());
            SmartDashboard.putNumber("vision/tag count", estimate.tagCount);
            SmartDashboard.putNumber("vision/avg tag dist", estimate.avgTagDist);
        }

        // Solve the shoot-on-the-move aim for this loop (after vision so it uses the
        // freshest pose). Everything downstream -- getHubHeading, getShotDistance,
        // readyToShoot, the shooter's table lookups -- reads this cached solution.
        updateShotSolution();

        // Update which side of the field the pass corner is on (0.5 m hysteresis band).
        double poseY = getState().Pose.getY();
        if (m_passHighSide && poseY < ShooterConstants.kFieldWidthMeters / 2.0 - 0.5) {
            m_passHighSide = false;
        } else if (!m_passHighSide && poseY > ShooterConstants.kFieldWidthMeters / 2.0 + 0.5) {
            m_passHighSide = true;
        }

        // === Dashboard diagnostics ===
        m_field.setRobotPose(getState().Pose);
        SmartDashboard.putNumber("dist to hub", this.getDistanceToClosestHub());
        SmartDashboard.putBoolean("hub visible", hubVisible);  // True if any tags detected
        SmartDashboard.putNumber("vision/pose resets", m_visionPoseResets);
        SmartDashboard.putBoolean("vision/heading seeded", m_headingSeededFromVision);
        // Aim sanity checks: WHICH hub the shot math is targeting and the heading it
        // wants. If "dist to hub" doesn't match a tape measure, everything downstream
        // (hood angle, RPS, aim) is being computed for the wrong target.
        Translation2d targetHub = getHubPosition();
        SmartDashboard.putNumber("aim/target hub x", targetHub.getX());
        SmartDashboard.putNumber("aim/target hub y", targetHub.getY());
        SmartDashboard.putNumber("aim/hub heading deg", getHubHeading().getDegrees());
        Translation2d passTarget = getPassTarget();
        SmartDashboard.putNumber("pass/target x", passTarget.getX());
        SmartDashboard.putNumber("pass/target y", passTarget.getY());
        SmartDashboard.putNumber("pass/distance", getPassDistance());
        // Hub-active state per the 2026 SHIFTS game data (cached for isOurHubActive(), which
        // gates the right-trigger context choice). Computed BEFORE the aim/auto mode string
        // below so the dashboard mirrors the exact condition a trigger pull would evaluate.
        double matchTime = DriverStation.getMatchTime();
        String gameData = effectiveGameData();
        m_ourHubActive = computeOurHubActive(matchTime, gameData);
        SmartDashboard.putBoolean("our hub active", m_ourHubActive);

        // What a right-trigger pull would do right now (the choice latches at the pull).
        // Mirrors the binding's condition exactly: in range AND in the alliance zone AND
        // our hub is active (during the opponent's shift a hub shot scores nothing, so
        // the pull ferries instead).
        boolean inAllianceZone = isInAllianceZone();
        SmartDashboard.putBoolean("aim/in alliance zone", inAllianceZone);
        SmartDashboard.putString("aim/auto mode",
            getShotDistance() <= ShooterConstants.kMaxShotDistanceMeters
                && inAllianceZone && m_ourHubActive
                ? "HUB" : "PASS");

        // Compute which alliance currently has active hub (Blue or Red)
        boolean blueHubActive = computeHubActiveForAlliance(Alliance.Blue, matchTime, gameData);
        String activeAlliance = blueHubActive ? "Blue" : "Red";
        SmartDashboard.putString("active hub alliance", activeAlliance);
    }

    // Cached each loop in periodic(). Defaults true so nothing is gated before the first
    // loop runs.
    private boolean m_ourHubActive = true;

    /** Whether our hub currently scores (2026 SHIFTS game data). True in auto, true in the
     *  shop (no game data -> assume active), false during the opponent's teleop shift. */
    public boolean isOurHubActive() {
        return m_ourHubActive;
    }

    // Game data to feed the SHIFTS logic. Real game data always wins. When it's empty:
    //   WITH FMS (real match, data not sent yet): keep it empty -- the compute treats that
    //     as "assume active", which is the safe default when we genuinely don't know the
    //     shift order yet. Never guess on a real field.
    //   WITHOUT FMS: synthesize 'B' so DS *practice mode* actually cycles the shifts --
    //     practice mode supplies a real teleop countdown, and with synthesized data the
    //     active/inactive swaps happen on schedule so drivers can rehearse them. ('B' =
    //     blue inactive first; type R or B into the DS setup tab's Game Data box to choose
    //     the order instead.) Plain teleop without a countdown reads matchTime = -1, which
    //     lands in the always-active window, so ordinary shop driving is unaffected.
    private String effectiveGameData() {
        String gameData = DriverStation.getGameSpecificMessage();
        if (gameData != null && !gameData.isEmpty()) {
            return gameData;
        }
        return DriverStation.isFMSAttached() ? "" : "B";
    }

    private boolean computeOurHubActive(double matchTime, String gameData) {
        return DriverStation.getAlliance()
            .map(alliance -> computeHubActiveForAlliance(alliance, matchTime, gameData))
            .orElse(false);
    }

    /** 2026 game-data hub logic: hubs alternate 25 s active shifts through teleop, with the
     *  order set by the first character of the game data ('R' = red inactive first). */
    private boolean computeHubActiveForAlliance(Alliance alliance, double matchTime, String gameData) {
        if (DriverStation.isAutonomous()) {
            return true;
        }
        if (!DriverStation.isTeleop()) {
            return false;
        }
        // If no game data yet, assume hub active (per WPILib guidance)
        if (gameData == null || gameData.isEmpty()) {
            return true;
        }
        boolean redInactiveFirst;
        switch (gameData.charAt(0)) {
            case 'R' -> redInactiveFirst = true;
            case 'B' -> redInactiveFirst = false;
            default -> {
                return true;
            }
        }

        boolean shift1Active = switch (alliance) {
            case Red -> !redInactiveFirst;
            case Blue -> redInactiveFirst;
        };

        // Teleop timeline (140 s countdown, verified against the WPILib 2026 game-data
        // reference implementation): 140-130 is the 10 s transition with both hubs active,
        // then four 25 s shifts, then both hubs active for the final 30 s (endgame).
        if (matchTime > 130) {
            return true;
        } else if (matchTime > 105) {
            return shift1Active;
        } else if (matchTime > 80) {
            return !shift1Active;
        } else if (matchTime > 55) {
            return shift1Active;
        } else if (matchTime > 30) {
            return !shift1Active;
        } else {
            return true;
        }
    }


    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }
    public double getDistanceToClosestHub() {
        return getState().Pose.getTranslation().getDistance(getHubPosition());
    }

    // Which hub to aim at. In a real match (FMS attached) it's the alliance hub. In the
    // shop it's whichever hub is CLOSER -- practice DSes routinely sit on the wrong
    // alliance, and aiming at the far hub (~9 m away) made the robot "aim forward" from
    // everywhere and clamped the shot tables at max range (max hood angle, max RPS).
    public Translation2d getHubPosition() {
        if (DriverStation.isFMSAttached()) {
            return DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red
                ? ShooterConstants.kRedHubPosition
                : ShooterConstants.kBlueHubPosition;
        }
        Translation2d robot = getState().Pose.getTranslation();
        return robot.getDistance(ShooterConstants.kBlueHubPosition)
                <= robot.getDistance(ShooterConstants.kRedHubPosition)
            ? ShooterConstants.kBlueHubPosition
            : ShooterConstants.kRedHubPosition;
    }

    // True when the robot is legally inside its own alliance zone; gates hub shots on
    // POSITION, not just distance (a robot past the barrier can still be within 5 m of its
    // hub). Which zone is "ours" comes from the driver-station alliance -- FMS-assigned in
    // a match, manually selected in the shop -- and the hub sits ON the zone line, so the
    // zone is everything between your wall and your hub's X. The pose is absolute
    // blue-origin and does NOT flip by alliance, hence the explicit per-alliance hub X.
    public boolean isInAllianceZone() {
        boolean red = DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red;
        double robotX = getState().Pose.getX();
        double hubX = (red ? ShooterConstants.kRedHubPosition
                           : ShooterConstants.kBlueHubPosition).getX();
        return red ? robotX >= hubX : robotX <= hubX;
    }

    // === Active self-test (pit motor test) ===
    // Rotates all four modules in place (steer test), then briefly drives forward (drive
    // test -- THE ROBOT MOVES; keep it on blocks or with a clear runway). Verifies each
    // module's steer angle reaches the commanded direction and each drive wheel actually
    // turns. Only meaningful while enabled; SystemsCheck guards that. Publishes pass/fail
    // per module under SystemsCheck/Drive/*.
    public Command selfTestCommand() {
        final SwerveRequest.PointWheelsAt point = new SwerveRequest.PointWheelsAt();
        final SwerveRequest.RobotCentric roll = new SwerveRequest.RobotCentric()
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage);
        final SwerveRequest.SwerveDriveBrake brake = new SwerveRequest.SwerveDriveBrake();
        return Commands.sequence(
            runOnce(() -> SmartDashboard.putString("SystemsCheck/Drive/Status",
                "steer test - wheels rotating in place")),
            applyRequest(() -> point.withModuleDirection(Rotation2d.fromDegrees(90))).withTimeout(0.9),
            runOnce(() -> checkSteerReached(90.0)),
            applyRequest(() -> point.withModuleDirection(Rotation2d.kZero)).withTimeout(0.6),
            runOnce(() -> SmartDashboard.putString("SystemsCheck/Drive/Status",
                "DRIVE test - ROBOT WILL MOVE")),
            applyRequest(() -> roll.withVelocityX(0.4).withVelocityY(0.0).withRotationalRate(0.0)).withTimeout(0.5),
            runOnce(this::checkDriveMoving),
            applyRequest(() -> brake).withTimeout(0.4),
            runOnce(() -> {
                boolean pass = true;
                for (String corner : kSelfTestCorners) {
                    pass = pass
                        && SmartDashboard.getBoolean("SystemsCheck/Drive/" + corner + "/Steer", false)
                        && SmartDashboard.getBoolean("SystemsCheck/Drive/" + corner + "/Drive", false);
                }
                SmartDashboard.putBoolean("SystemsCheck/Drive/Pass", pass);
                SmartDashboard.putString("SystemsCheck/Drive/Status", pass ? "PASS" : "FAIL");
            })
        ).finallyDo(() -> setControl(new SwerveRequest.Idle()));
    }

    private static final String[] kSelfTestCorners = {"FrontLeft", "FrontRight", "BackLeft", "BackRight"};

    // Each module's steer angle is within tolerance of the commanded direction, folded to
    // ±90: steer optimization may legally point a module 180 degrees opposite (with drive
    // reversed) whenever that's the shorter rotation -- e.g. wheels left at X-lock's ±45
    // flip when commanded to 90. Both orientations are a working steer motor, so the error
    // is computed modulo 180 and a reversed module passes.
    private void checkSteerReached(double targetDeg) {
        for (int i = 0; i < kSelfTestCorners.length; i++) {
            double angleDeg = getModule(i).getCurrentState().angle.getDegrees();
            double errDeg = Math.abs(MathUtil.inputModulus(angleDeg - targetDeg, -90.0, 90.0));
            SmartDashboard.putBoolean("SystemsCheck/Drive/" + kSelfTestCorners[i] + "/Steer", errDeg < 10.0);
        }
    }

    // Each module's drive wheel is actually turning.
    private void checkDriveMoving() {
        for (int i = 0; i < kSelfTestCorners.length; i++) {
            double speed = Math.abs(getModule(i).getCurrentState().speedMetersPerSecond);
            SmartDashboard.putBoolean("SystemsCheck/Drive/" + kSelfTestCorners[i] + "/Drive", speed > 0.1);
        }
    }

    public ChassisSpeeds getFieldRelativeSpeeds() {
        return ChassisSpeeds.fromRobotRelativeSpeeds(getState().Speeds, getState().Pose.getRotation());
    }

    // === Shoot-on-the-move solution ===
    // shotVector = (hub - robot) - robotVelocity * lead * TOF: the displacement the ball
    // must cover in the robot's frame so it lands on the hub even though the robot is
    // moving. Solved ONCE per loop in updateShotSolution(); the getters below return the
    // cached solution. It used to be re-derived 5-6 times per loop straight from raw
    // module-state speeds, which is where the on-the-move twitchiness came from:
    //   - raw swerve speeds are noisy, and every wiggle went straight into the aim target
    //     the heading controller was chasing at P=8
    //   - TOF was looked up at the RAW hub distance while the table lookup used the led
    //     distance, so the lead itself was computed with the wrong flight time
    private void updateShotSolution() {
        Translation2d robotToHub = getHubPosition().minus(getState().Pose.getTranslation());

        // Low-pass the field velocity used for lead (~0.15 s time constant): the aim
        // target follows real acceleration but stops chattering with module noise.
        ChassisSpeeds speeds = getFieldRelativeSpeeds();
        Translation2d lead = new Translation2d(
            m_shotVelFilterX.calculate(speeds.vxMetersPerSecond),
            m_shotVelFilterY.calculate(speeds.vyMetersPerSecond)
        ).times(m_moveCompGain.get());
        // FeatureFlags.ShootOnTheMove off -> zero the lead (aim as if stationary). The
        // filters still run above so they stay warm if it's toggled back on mid-match.
        if (!FeatureFlags.SHOOT_ON_THE_MOVE.getAsBoolean()) {
            lead = new Translation2d();
        }

        // Fixed-point iteration: lead depends on TOF, TOF depends on the led distance.
        // Converges in 2-3 passes at any legal robot speed.
        double tofOffset = SmartDashboard.getNumber(ShooterConstants.kTimeOfFlightOffsetKey, 0);
        double tof = Math.max(0.001, ShooterConstants.getShotTimeOfFlightSeconds(robotToHub.getNorm()) + tofOffset);
        Translation2d shotVector = robotToHub;
        for (int i = 0; i < 3; i++) {
            shotVector = robotToHub.minus(lead.times(tof));
            tof = Math.max(0.001, ShooterConstants.getShotTimeOfFlightSeconds(shotVector.getNorm()) + tofOffset);
        }

        m_shotVector = shotVector;
        m_shotTofSeconds = tof;
    }

    public double getShotTimeOfFlightSeconds() {
        return m_shotTofSeconds;
    }

    public Translation2d getMotionCompensatedShotVector() {
        return m_shotVector;
    }

    // === Compensated hub position (for visualization) ===
    // Where the hub will be in TOF seconds, given current robot motion.
    public Translation2d getCompensatedHubPosition() {
        return getState().Pose.getTranslation().plus(getMotionCompensatedShotVector());
    }

    // === Shot distance ===
    // Magnitude of the compensated shot vector, clamped to the table's valid range (0–6 m).
    public double getShotDistance() {
        return MathUtil.clamp(getMotionCompensatedShotVector().getNorm(), 0, 6);
    }


    // === Shot heading ===
    // Bearing of the motion-compensated shot vector, plus the fixed mechanical offset.
    //
    // NOTE: this used to add an "aim ahead while spinning" term (gyro rate x TOF). It was
    // removed on purpose -- do not add it back into this target. Two reasons:
    //   1. Feedback loop: the heading controller's own rotation fed the term, which pushed
    //      the target further ahead, which sped the rotation up (loop gain ~ P*TOF ~ 6).
    //      The robot oscillated around the hub and could never settle on it.
    //   2. Units: Pigeon getAngularVelocityZWorld() returns degrees/sec and the term used
    //      it as radians, so any rotation at all pinned the target 20 deg off the hub.
    // faceHubCommand drives the spin toward zero before the shot fires, so a spin term has
    // no value in the live aiming target. If spin compensation is ever truly needed, apply
    // it once at ball release, never inside the target the controller is chasing.
    public Rotation2d getHubHeading() {
        return getMotionCompensatedShotVector().getAngle()
            .plus(Rotation2d.fromDegrees(m_headingOffsetDeg.get()));
    }

    // === Heading error ===
    // How far off the robot's current heading is from the computed shot heading.
    // This is the readiness gate for aim (must be within 5°).
    public Rotation2d getHubHeadingError() {
        return Rotation2d.fromRadians(
            MathUtil.angleModulus(getHubHeading().minus(getState().Pose.getRotation()).getRadians())
        );
    }

    // === Face hub command ===
    // Heading-locked drive: the heading snaps to the computed hub heading (with PID stiffness),
    // while the driver retains full translation control. Used during aiming and charging shots.
    public Command faceHubCommand(Supplier<Double> xVelocity, Supplier<Double> yVelocity) {
        return applyRequest(() -> snapRequest
            .withVelocityX(xVelocity.get())
            .withVelocityY(yVelocity.get())
            .withDeadband(Constants.kMaxSpeed * 0.1)
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage)
            .withTargetDirection(fieldToOperatorBearing(getHubHeading()))
        );
    }

    // === Passing target ===
    // Ferry landing point: the alliance-zone corner on whichever side of the field the
    // robot is currently on (left side -> left corner, right side -> right corner, with
    // hysteresis at the centerline), inset from the walls so balls land in the zone
    // instead of ricocheting off the corner. Own alliance end comes from the DS setting.
    public Translation2d getPassTarget() {
        boolean red = DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red;
        double inset = m_passCornerInset.get();
        double x = red
            ? ShooterConstants.kFieldLengthMeters - inset
            : inset;
        double y = m_passHighSide
            ? ShooterConstants.kFieldWidthMeters - inset
            : inset;
        return new Translation2d(x, y);
    }

    public double getPassDistance() {
        return getPassTarget().getDistance(getState().Pose.getTranslation());
    }

    // Pass aim is a straight bearing to the landing corner (no motion lead: a pass lands
    // in a zone, not a hub opening). The same mechanical heading trim applies.
    public Rotation2d getPassHeading() {
        return getPassTarget().minus(getState().Pose.getTranslation()).getAngle()
            .plus(Rotation2d.fromDegrees(m_headingOffsetDeg.get()));
    }

    public Rotation2d getPassHeadingError() {
        return Rotation2d.fromRadians(
            MathUtil.angleModulus(getPassHeading().minus(getState().Pose.getRotation()).getRadians())
        );
    }

    // Heading-locked drive toward the pass corner; driver keeps translation control.
    public Command facePassTargetCommand(Supplier<Double> xVelocity, Supplier<Double> yVelocity) {
        return applyRequest(() -> snapRequest
            .withVelocityX(xVelocity.get())
            .withVelocityY(yVelocity.get())
            .withDeadband(Constants.kMaxSpeed * 0.1)
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage)
            .withTargetDirection(fieldToOperatorBearing(getPassHeading()))
        );
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}

