package frc.robot.subsystems.drive;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Function;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.commands.PathfindingCommand;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

import frc.robot.Constants;
import frc.robot.subsystems.drive.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.localisation.LimelightHelpers;
import frc.robot.subsystems.localisation.LimelightInfo;
import frc.robot.subsystems.localisation.LocalisationConstants;
import frc.robot.subsystems.shooter.ShooterConstants;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private final Field2d m_field = new Field2d();
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();
    // Heading-locked drive request shared by faceHubCommand; PID configured in configureAutoBuilder.
    private final SwerveRequest.FieldCentricFacingAngle snapRequest = new SwerveRequest.FieldCentricFacingAngle();
    private Function<String, LimelightHelpers.PoseEstimate> limelightGetBotPoseEstimate =
        LimelightHelpers::getBotPoseEstimate_wpiBlue;
    private int m_rejectedVisionMeasurements = 0;

    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;
    private Optional<Alliance> m_lastAlliance = Optional.empty();

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),
                    // PID constants for rotation
                    new PIDConstants(7, 0, 0)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }

        setLimelightPerspective(DriverStation.getAlliance().orElse(Alliance.Blue));
        m_lastAlliance = Optional.of(DriverStation.getAlliance().orElse(Alliance.Blue));
        updateAllianceDependentState();
        snapRequest.HeadingController.setP(8);
        snapRequest.HeadingController.enableContinuousInput(-Math.PI, Math.PI);

        SmartDashboard.putData("Field", m_field);
        CommandScheduler.getInstance().schedule(PathfindingCommand.warmupCommand());
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    private void setLimelightPerspective(Alliance alliance) {
        limelightGetBotPoseEstimate = alliance == Alliance.Red
            ? LimelightHelpers::getBotPoseEstimate_wpiRed
            : LimelightHelpers::getBotPoseEstimate_wpiBlue;
    }

    private void updateAllianceDependentState() {
        DriverStation.getAlliance().ifPresent(allianceColor -> {
            if (!m_lastAlliance.equals(Optional.of(allianceColor))) {
                setLimelightPerspective(allianceColor);
                m_lastAlliance = Optional.of(allianceColor);
            }

            if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            }
        });
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        updateAllianceDependentState();

        boolean hubVisible = false;
        for (LimelightInfo limelight : LocalisationConstants.kLimelights) {
            LimelightHelpers.SetRobotOrientation(
                    limelight.name(), getState().Pose.getRotation().getDegrees(), 
                    getPigeon2().getAngularVelocityZWorld().getValueAsDouble(), 
                    0, 0, 0, 0
                );

            final LimelightHelpers.PoseEstimate estimate = limelightGetBotPoseEstimate.apply(limelight.name());

            if (estimate == null) {
                continue;
            }
            if (estimate.tagCount > 0) {
                hubVisible = true;
                double poseDelta = estimate.pose.getTranslation().getDistance(getState().Pose.getTranslation());
                if (poseDelta > ShooterConstants.kMaxVisionCorrectionMeters) {
                    m_rejectedVisionMeasurements++;
                    continue;
                }

                final double xyStdDev;
                if (estimate.avgTagDist > 0.125 && estimate.avgTagArea < 2.5) {
                    xyStdDev = 0.25;
                } else {
                    xyStdDev = Math.pow(0.6, estimate.avgTagDist + 1);
                }

                addVisionMeasurement(estimate.pose, estimate.timestampSeconds, VecBuilder.fill(xyStdDev, xyStdDev, Double.MAX_VALUE));
            }
        }

        m_field.setRobotPose(getState().Pose);
        SmartDashboard.putNumber("dist to hub", this.getDistanceToClosestHub());
        SmartDashboard.putBoolean("hub visible", hubVisible);
        SmartDashboard.putNumber("rejected vision measurements", m_rejectedVisionMeasurements);
        // Publish which alliance's hub is currently active per 2026 Game Data logic
        double matchTime = DriverStation.getMatchTime();
        String gameData = DriverStation.getGameSpecificMessage();

        boolean ourHubActive = computeOurHubActive(matchTime, gameData);
        SmartDashboard.putBoolean("our hub active", ourHubActive);

        // Compute which alliance currently has active hub (Blue or Red)
        boolean blueHubActive = computeHubActiveForAlliance(Alliance.Blue, matchTime, gameData);
        String activeAlliance = blueHubActive ? "Blue" : "Red";
        SmartDashboard.putString("active hub alliance", activeAlliance);
    }

    private boolean computeOurHubActive(double matchTime, String gameData) {
        return DriverStation.getAlliance()
            .map(alliance -> computeHubActiveForAlliance(alliance, matchTime, gameData))
            .orElse(false);
    }

    /** 2026 game-data hub logic: hubs alternate 25 s active shifts through teleop, with the
     *  order set by the first character of the game data ('R' = red inactive first). */
    private boolean computeHubActiveForAlliance(Alliance alliance, double matchTime, String gameData) {
        if (DriverStation.isAutonomous()) {
            return true;
        }
        if (!DriverStation.isTeleop()) {
            return false;
        }
        // If no game data yet, assume hub active (per WPILib guidance)
        if (gameData == null || gameData.isEmpty()) {
            return true;
        }
        boolean redInactiveFirst;
        switch (gameData.charAt(0)) {
            case 'R' -> redInactiveFirst = true;
            case 'B' -> redInactiveFirst = false;
            default -> {
                return true;
            }
        }

        boolean shift1Active = switch (alliance) {
            case Red -> !redInactiveFirst;
            case Blue -> redInactiveFirst;
        };

        if (matchTime > 130) {
            return true;
        } else if (matchTime > 105) {
            return shift1Active;
        } else if (matchTime > 80) {
            return !shift1Active;
        } else if (matchTime > 55) {
            return shift1Active;
        } else if (matchTime > 30) {
            return !shift1Active;
        } else {
            return true;
        }
    }


    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }
    public Command setPose(Pose2d pose) {
       return runOnce(() -> this.resetPose(pose));
    }

    public double getDistanceToClosestHub() {
        return getState().Pose.getTranslation().getDistance(getHubPosition());
    }

    public Translation2d getHubPosition() {
        return DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red
            ? ShooterConstants.kRedHubPosition
            : ShooterConstants.kBlueHubPosition;
    }

    public ChassisSpeeds getFieldRelativeSpeeds() {
        return ChassisSpeeds.fromRobotRelativeSpeeds(getState().Speeds, getState().Pose.getRotation());
    }

    public double getShotTimeOfFlightSeconds() {
        double offset = SmartDashboard.getNumber(ShooterConstants.kTimeOfFlightOffsetKey, 0);
        return Math.max(0.001, ShooterConstants.getShotTimeOfFlightSeconds(getDistanceToClosestHub()) + offset);
    }

    public Translation2d getMotionCompensatedShotVector() {
        Translation2d robotToHub = getHubPosition().minus(getState().Pose.getTranslation());
        double timeOfFlight = getShotTimeOfFlightSeconds();
        ChassisSpeeds fieldSpeeds = getFieldRelativeSpeeds();

        Translation2d requiredFieldVelocity = robotToHub.div(timeOfFlight);
        Translation2d requiredRobotRelativeShotVelocity = requiredFieldVelocity.minus(
            new Translation2d(fieldSpeeds.vxMetersPerSecond, fieldSpeeds.vyMetersPerSecond)
        );

        return requiredRobotRelativeShotVelocity.times(timeOfFlight);
    }

    public Translation2d getCompensatedHubPosition() {
        return getState().Pose.getTranslation().plus(getMotionCompensatedShotVector());
    }

    public double getShotDistance() {
        return MathUtil.clamp(getMotionCompensatedShotVector().getNorm(), 0, 6);
    }

    public Rotation2d getHubHeading() {
        Rotation2d shotHeading = getMotionCompensatedShotVector().getAngle();
        // Compensate for robot rotation during ball time-of-flight
        double timeOfFlight = getShotTimeOfFlightSeconds();
        // Angular velocity in radians/sec (world Z). Use pigeon/gyro reading available via getPigeon2()
        double angularRateRadPerSec = 0.0;
        try {
            angularRateRadPerSec = getPigeon2().getAngularVelocityZWorld().getValueAsDouble();
        } catch (Exception ex) {
            // If gyro not available for any reason, fall back to zero compensation
            angularRateRadPerSec = 0.0;
        }

        double rotationalCompensation = angularRateRadPerSec * timeOfFlight;
        // Allow tuning via SmartDashboard (default ~0.35 rad = ~20°)
        double maxComp = SmartDashboard.getNumber("ShotTuning/MaxRotationalCompRad", 0.35);
        rotationalCompensation = Math.max(-maxComp, Math.min(maxComp, rotationalCompensation));

        Rotation2d compensatedHeading = shotHeading.plus(Rotation2d.fromRadians(rotationalCompensation));
        // Publish the compensation applied in degrees for debugging
        SmartDashboard.putNumber("rotational compensation deg", Math.toDegrees(rotationalCompensation));
        return compensatedHeading.plus(Rotation2d.fromRadians(ShooterConstants.kShooterHeadingOffsetRadians));
    }

    public Rotation2d getHubHeadingError() {
        return Rotation2d.fromRadians(
            MathUtil.angleModulus(getHubHeading().minus(getState().Pose.getRotation()).getRadians())
        );
    }

    public Command faceHubCommand(Supplier<Double> xVelocity, Supplier<Double> yVelocity) {
        return applyRequest(() -> snapRequest
            .withVelocityX(xVelocity.get())
            .withVelocityY(yVelocity.get())
            .withDeadband(Constants.kMaxSpeed * 0.1)
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage)
            .withTargetDirection(getHubHeading())
        );
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}

